development:
  domain: localhost:3000
  locker: tmp/development_locker
  tank: tmp/development_tank
  stable_interval: 2
  watcher_persist: tmp/development_watcher.yml
  repository_pairtree: tmp/development_repository_pairtree
  access_pairtree: public/development_access_pairtree
  access_image_size: 300x300
  access_image_format: jpg
  ead_url: http://www.lib.ncsu.edu/findingaids
  
test:
  domain: test.host
  locker: tmp/test_locker
  tank: tmp/test_tank
  stable_interval: 2
  watcher_persist: tmp/test_watcher.yml
  repository_pairtree: tmp/test_repository_pairtree
  access_pairtree: public/test_access_pairtree
  access_image_size: 300x300
  access_image_format: jpg
  ead_url: http://www.lib.ncsu.edu/findingaids

production:
  domain: example.com
